steps:
  - name: python
    entrypoint: pip
    args: ["install", "-r", "requirements.txt", "--user"]
  - name: python
    entrypoint: python
    args: ["-m", "pytest", "-v"]
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/webapp-repo/webapp:$TAG_NAME', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/$PROJECT_ID/webapp-repo/webapp:$TAG_NAME']
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args: 
      - 'run'
      - 'deploy'
      - 'webapp'
      - '--region'
      - 'us-central1'
      - '--port'
      - '8080'
      - '--allow-unauthenticated'
    images:
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/webapp-repo/webapp:$TAG_NAME'